steps:

  #
  # Android builder base - used by React Native and React Native CLI
  #
  - label: ':docker: Build Android Builder base image'
    key: 'android-builder-base'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build: android-builder-base
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  android-builder-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base
      - docker-compose#v3.3.0:
          push: android-builder-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base

  #
  # Publish/package notifier
  #
  - label: ':docker: Prepare package.json'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    key: 'package-js'
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v3.7.0:
          run: minimal-packager
    artifact_paths: min_packages.tar

  - label: ':docker: Build and publish JS packages'
    key: 'publish-js'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build: publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
    env:
      BUILD_RN_WITH_LATEST_NATIVES: ${BUILD_RN_WITH_LATEST_NATIVES}


  #
  # Trigger individual pipelines
  #
  - label: 'Trigger React Native pipeline'
    depends_on:
      - 'publish-js'
      - 'android-builder-base'
    trigger: 'bugsnag-js-react-native'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true
